namespace: student-registration

backend:
  replicaCount: 2

  image:
    repository: anuragpatilcloud/backend
    tag: "17"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8080

frontend:
  replicaCount: 2

  image:
    repository: anuragpatilcloud/frontend
    tag: "17"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true

  className: alb

  host: ""

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
