apiVersion: v1
kind: Service

metadata:
  name: student-registration-backend
  namespace: student-registration

spec:
  type: ClusterIP

  selector:
    app: student-registration-backend

  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
